# Generated by Django 4.1.3 on 2023-03-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_produto_data_saida_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_chegada',
            field=models.DateField(),
        ),
    ]
