# Generated by Django 4.1.3 on 2023-03-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_produto_preco_unitario_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
