# Generated by Django 5.0.7 on 2024-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_produto_preco_unitario_alter_produto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='descrição'),
        ),
    ]
