# Generated by Django 5.1.6 on 2025-08-02 20:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_venda_cliente_alter_produto_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
